test_frontend:
  before_script:
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - apt-get update -qq && apt-get install -y -qq yarn
    - cd assembl/static2 && yarn
  script:
    - cd assembl/static2
    - yarn run test
