image: python:2.7

stages:
  - test
  - push_to_master
  - build
  - deploy_to_dev
  - test_on_dev
  - deploy_to_uat
  - deploy_to_prod

cache:
  paths:
    - assembl/static2/node_modules/
    - /usr/local/share/.cache/yarn/v2

test_frontend:
  stage: test
  except:
    - master
  image: node:8
  before_script:
    - export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    - cd assembl/static2
    - yarn
  script:
    - yarn run test
    - yarn run eslint
    - yarn run stylelint
    - yarn run flow --quiet

test_integration_and_ui:
  stage: test_on_dev
  image: node:8
  before_script:
    - eval $(ssh-agent -s) && sh scripts/configure_ssh.sh
    - sh scripts/prepare_integration_tests.sh
  script:
    # run integration tests
    - yarn jest tests/integration
    # run each ui test one by one
    - yarn runinband
variables:
  DEVELOP_BRANCH: add_build_job
  MASTER_BRANCH: tmp_master_for_ci_cd

build_wheel:
  # TODO: urlmetadata
  # TODO: pass the assembl version to the other jobs
  # variables:
  #   CI_DEBUG_TRACE: "true"
  stage: build
  only:
    - add_build_job
  before_script:
    - sh scripts/install_build_dependencies.sh
    - sh scripts/install_node_and_yarn.sh
    - sh scripts/configure_assembl_remote.sh
    - eval $(ssh-agent -s) && sh scripts/configure_ssh.sh
    - sh scripts/clear_apt_cache.sh
  script:
    # bump the version, merge to master
    - sh scripts/bump_assembl_version_and_push.sh
    # create the wheel and upload to pypi
    - sh scripts/create_assembl_wheel.sh
    - twine upload -u bluenove --skip-existing dist/*
