image: python:2.7

stages:
  - test
  - push_to_master
  - build
  - deploy_to_dev
  - test_on_dev
  - deploy_to_uat
  - deploy_to_prod

cache:
  paths:
    - assembl/static2/node_modules/
    - /usr/local/share/.cache/yarn/v2

test_frontend:
  image: node:8
  before_script:
    - export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    - cd assembl/static2
    - yarn
    - yarn cache dir
  script:
    - yarn run test
    - yarn run eslint
    - yarn run stylelint
    - yarn run flow --quiet
