image: python:2.7

test_frontend:
  before_script:
    - apt-get update -qq && apt-get install -y -qq nodejs
    - cd assembl/static2 && npm install
  script:
    - cd assembl/static2
    - npm run test

# push to master:
#   stage: pushtomaster
#   only:
#     - develop
#   script:
#     - chmod +x scripts/git-push
#     - scripts/git-push git@github.com:assembl/assembl.git
#   when: on_success
