image: python:2.7

cache:
  paths:
    - assembl/static2/node_modules/

test_frontend:
  image: node:8
  before_script:
    - export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    - cd assembl/static2
    - yarn
  script:
    - yarn run test
    - yarn run eslint
    - yarn run stylelint
    - yarn run flow

test_manual:
  when: manual
  script: echo "Deployment OK"
