language: python
sudo: required
dist: trusty
addons:
  ssh_known_hosts: localhost
  postgresql: "9.5"
#cache: pip
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y fabric git openssh-server
 #- sudo apt-get install -y postgresql
 - sudo /etc/init.d/postgresql restart
 - sudo apt-get install apt-transport-https
 - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee -a /etc/apt/sources.list.d/yarn.list
 - sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
 - sudo apt-get -qq update
 - sudo apt-get install yarn
 - sudo apt-get install -y python-virtualenv python-pip python-psycopg2
 - sudo apt-get install -y python-requests python-jinja2 git
 - sudo apt-get install -y build-essential python-dev pandoc
 - sudo apt-get install -y automake bison flex gperf gawk
 - sudo apt-get install -y graphviz pkg-config gfortran
 - sudo apt-get install -y chromium-chromedriver
 - sudo apt-get install -y libpq-dev libmemcached-dev libzmq3-dev libxslt1-dev libffi-dev libhiredis-dev libxml2-dev libssl-dev libreadline-dev liblapack-dev libatlas-dev libblas-dev libgraphviz-dev libxmlsec1-dev
 - sudo apt-get install -y redis-server
 - sudo /etc/init.d/redis-server start
 - sudo apt-get install -y memcached
 - sudo /etc/init.d/memcached start
 #- fab -c configs/develop.rc bootstrap_from_checkout
 - ssh-keygen -P '' -f ~/.ssh/id_rsa && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
 - echo "_extends = ./testing.rc" > configs/travis.rc; echo "_gitbranch = travis" >> configs/travis.rc;
 - git fetch --unshallow
 - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"; git fetch origin
 - git fetch origin travis
 - git checkout travis
 - git pull
 - git submodule update --init
 - ls -lha /home/travis/build/assembl/assembl/assembl/scripts/pypsql.py
 - fab -c configs/travis.rc update_pip_requirements
 - fab -c configs/travis.rc bootstrap_from_checkout
install: true
before_script:
 - source venv/bin/activate
 - supervisord
script: true
