language: python
sudo: required
dist: trusty
addons:
  ssh_known_hosts: localhost
  postgresql: "9.5"
cache: pip
before_install:
 - sudo usermod -a -G www-data $USER
 - sudo apt-get -qq update
 - sudo apt-get install -y fabric git openssh-server
 #- sudo apt-get install -y postgresql
 - sudo /etc/init.d/postgresql restart
 - sudo apt-get install apt-transport-https
 - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee -a /etc/apt/sources.list.d/yarn.list
 - sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
 - sudo apt-get -qq update
 - sudo apt-get install yarn
 - sudo apt-get install -y python-virtualenv python-pip python-psycopg2
 - sudo apt-get install -y python-requests python-jinja2 git
 - sudo apt-get install -y build-essential python-dev pandoc
 - sudo apt-get install -y automake bison flex gperf gawk
 - sudo apt-get install -y graphviz pkg-config gfortran
 - sudo apt-get install -y chromium-chromedriver
 - sudo apt-get install -y libpq-dev libmemcached-dev libzmq3-dev libxslt1-dev libffi-dev libhiredis-dev libxml2-dev libssl-dev libreadline-dev liblapack-dev libatlas-dev libblas-dev libgraphviz-dev libxmlsec1-dev
 - sudo apt-get install -y redis-server
 - sudo /etc/init.d/redis-server start
 - sudo apt-get install -y memcached
 - sudo /etc/init.d/memcached start
 - ssh-keygen -P '' -f ~/.ssh/id_rsa && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
 - echo "_extends = ./testing.rc" > configs/travis.rc; echo "_gitbranch = travis" >> configs/travis.rc;
 - git fetch --unshallow
 - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"; git fetch origin
 - git fetch origin travis
 - git checkout travis
 - git pull
 - git submodule update --init
install:
 - fab -c configs/travis.rc update_pip_requirements
 #- fab -c configs/travis.rc set_file_permissions
 - sudo -E su $USER -c 'fab -c configs/travis.rc set_file_permissions'
 # TODO: fix fabfile's check_and_create_database_user command
 - python2 $PWD/assembl/scripts/pypsql.py -u postgres -n localhost  "CREATE USER assembl_test WITH CREATEDB ENCRYPTED PASSWORD 'assembl_test'; COMMIT;"
 - fab -c configs/travis.rc bootstrap_from_checkout
before_script:
  - source $VIRTUAL_ENV/bin/activate
  #- supervisord
  #- supervisorctl shutdown
  #- fab -c configs/travis.rc database_delete
  #- fab -c configs/travis.rc app_update_dependencies
  #- fab -c configs/travis.rc app_compile_nodbupdate
  - fab -c configs/travis.rc database_create
  - assembl-db-manage testing.ini bootstrap
script:
  # TODO: fix error (production.ini: Bad value substitution)
  # fab -c configs/travis.rc build_doc
  - py.test --cov assembl --cov-report term --cov-report html --junit-xml junit.xml assembl
  - cd assembl/static2; npm test; npm run eslint; cd ..
  - supervisorctl shutdown
