version: "2"
services:
  supervisor:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    volumes:
      - ..:/assembl
    links:
      - database
  bootstrap:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    volumes:
      - ..:/assembl
    links:
      - database
    command: /bin/sh -c '/etc/init.d/ssh start && /usr/bin/ssh-keyscan localhost && /usr/bin/fab -c ./configs/develop.rc bootstrap_from_checkout'
  cli:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    volumes:
      - ..:/assembl
      - ../dev_home:/home/assembl_user
    links:
      - database
      - supervisor
    hostname: dev-cli
  database:
    image: postgres:9.5.5-alpine
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
